### ISSUE TITLE
Page: overview

### ISSUE THREAD

**Issue by franc3000** [franc3000/bartok#12]
New page that displays the overview of a region.

```
select * from regions
```

Results:
```
id  region_name  counties    dataset states  client  complete  preferences
82  CO-Jake      EL PASO     sow003  CO      Jake    1         {"min_sqft": 1000}
```

Heat map, using the latitude longitude from the following query, where dataset is set by the region. E.g. `sow003`:

```
select t.*, s.lat, s.lon
from target t
inner join sold_append s
on t.property_address = s.property_address
where t.dataset='sow003'
and s.dataset='sow003'
and t.target_manual=1
```

**Comment by franc3000** [comment]
Using bootstrap datatables, display the following tables:

```
select owner_occupied, count(*) n from sold_append where dataset='sow003' group by 1;
```

```
select owner_occupied, count(*) n from master_append where dataset='sow003' group by 1;
```

**Comment by nmb10** [comment]
@franc3000  The table is 'regions', not 'region'. Isn't it?

**Comment by nmb10** [comment]
@franc3000 
```sql
select show columns from regions;
```
```
...
('preferences', 'varchar(255)', 'YES', '', None, '')]
...
```
255 for JSON? Is it enough?

**Comment by nmb10** [comment]
@franc3000 
* Problem

Problems converting json string to python dict: 
```python
(Pdb) json.loads(co_jake.preferences)
*** ValueError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

* Solution

Always use double quotes to wrap properties:
```
{"min_sqft":1000} instead of {'min_sqft':1000}
```
See http://stackoverflow.com/questions/949449/json-spec-does-the-key-have-to-be-surrounded-with-quotes for details.

**Comment by franc3000** [comment]
@nmb10 
table is `regions`
I changed the column for preferences to `text`
I changed the quotes to `"`

**Comment by nmb10** [comment]
Done. http://bartok.herokuapp.com/regions/overview/CO-Jake . 

 Questions to @franc3000 :
* region detail saves dataset to tmp file:
```python
        df.to_csv('temp.csv')
```
Why?

* Heat data requires dataset, but regions.dataset may be null. Does it make any sence for region to be without dataset?

* regions.region_name may be null. How do you use regions without name?

* target.last_market_sale_date stores date, but column is varchar(200). Why DATE type is not used here?

* It looks like target.target_manual takes 0/1 only. Why is it bigint instead of boolean?

**Comment by franc3000** [comment]
- `df.to_csv` was for local testing, you can remove

- heat data doesn't need a dataset. yes, regions can exist without a dataset.
we can have heat data for a city, and no master_append or sold_append dataset for it, but it exists in neighborhoods and with consumerview.

this query does not have a dataset:

```
select if(`mosaic_household` = 'S69', 1, 0) mosaic_s69, lat, lon
from consumerview
where state='TX'
and city='DALLAS'
and mosaic_household = 'S69';
```

- regions.region_name should not be able to be NULL

- to change target.last_market_sale_date to date, it has to be changed throughout the entire system. it is used in many tables. this can be an issue to fix later.

- target.target_manual is 0,1 now but it needs to accomodate multiclass classification

**Comment by nmb10** [comment]
Done.
