### ISSUE TITLE
Region detail display page loading speed is extremely slow.

### ISSUE THREAD

**Issue by nmb10** [franc3000/bartok#16]
http://127.0.0.1:5000/regions/CO-Jake (dataset has about 2500 rows).
It takes about 2 min to load on my machine.

**Comment by nmb10** [comment]
Done. I did it different way - render table using ajax. Now it has reasonable load time. What do you think, @franc3000 ?

**Comment by franc3000** [comment]
@nmb10 ajax is loading faster, thank you

**Comment by franc3000** [comment]
@nmb10 Please set the max "Last Market Sale Price" for the slider to the max actual price + 1
