### ISSUE TITLE
Manage synchronization of bartok models and db schema.

### ISSUE THREAD

**Issue by nmb10** [franc3000/bartok#17]
bartok models: regions.models.Region, regions.models.Target. We need the way how to synchronize them with existing db tables (regions, target).

**Comment by franc3000** [comment]
@nmb10 is this for db migration commands? i'm not sure how to

**Comment by nmb10** [comment]
@franc3000 

Here is the flask-migrations (sqlalchemy migrations actually) workflow. Developer1 implements new feature with db schema changes. He prepares migration, and commits it. Now when another developer wants to update bartok, he updates repo, and upgrades local db (manage.py upgrade). Also, it helps when you have more than one bartok installations (test, prod). In such case you behave the same: update bartok, upgrade db. Also, each migration allows to downgrade - it is useful sometimes.

This is how the flask-migrations work. How do you manage your changes now?

**Comment by franc3000** [comment]
We will create a new issue for each change in the schema, and you can implement the migration
