### ISSUE TITLE
Models pages

### ISSUE THREAD

**Issue by franc3000** [franc3000/bartok#19]
Create main page to display content from tables in db `models_investor`. Tables include:
- all_modeling
- investor_{primarykey}_test

Routes are:
- /models_investor/main.html
- /models_investor/positives/{primarykey}
- /models_investor/false_positives/{primarykey}

Design is similar to `targets`

Use http://datatables.net/

Add filtering, like in `regions` so that  it will only show the rows that have matching `description`.

Sortable tables, so they can be sorted by timestamp column.

### main.html

Displayed in the table:
id, timestamp, model_type, description, settings, roc_auc, link to positives page, link to false positives page

```
select id, timestamp, model_type, description, settings, roc_auc
from models_investor.all_modeling;
```

Using the primary key from the `models_investor.all_modeling` table, create links to the following pages

### positives.html

investor_21_test table is for primary key = 21:

```
select * from investor_21_test where y_test=1;
```

### false_positives.html

investor_21_test table is for primary key = 21:

```
select * from investor_21_test where y_test=0 and p_pctile > 75;
```

**Comment by nmb10** [comment]
Done. Check `Models` link in the main menu.

**Comment by franc3000** [comment]
http://bartok.herokuapp.com/models/investor/92/positives

Sorting by 'p_1' does not work correctly
'p_pctile' does not sort
Looks like sorting is not implemented

**Comment by franc3000** [comment]
Formatting:

`p_1` #.###0
`p_pctile` #.#0

Center align columns:
index
y_test
p_1
p_pctile
include

Right align columns:
last_market_sale_date
bldg_living_area	
combined_age_relative	
year_built	
combined_age	
total_assessed_value

**Comment by nmb10** [comment]
Done.
