### ISSUE TITLE
Heat map

### ISSUE THREAD

**Issue by franc3000** [franc3000/bartok#2]
Feature that takes a DataFrame of ['lat','lon','value'] and generates a heat map.

After the heat map is generated, plot the polygons for neighborhoods on top of the same map.

Example:

![sacramento_prices_heatmap_w_neighborhoods-535x559](https://cloud.githubusercontent.com/assets/10376582/13548914/b63f0926-e2c0-11e5-8598-ed984373f565.jpg)

**Comment by franc3000** [comment]
From the MySQL database, this would be a good test for the heat map:

```
select if(`mosaic_household` = 'S69', 1, 0) mosaic_s69, lat, lon
from consumerview
where state='TX'
and city='DALLAS'
and mosaic_household = 'S69';
```

**Comment by nmb10** [comment]
Done for TX/Dallas. @franc3000  should I always set mosaic_household?

**Comment by franc3000** [comment]
Yes, we always want the heat maps. I will create a new issue for changing the mosaic value from 'S69'  to the other options, like 'A01', 'A02', etc.
