### ISSUE TITLE
Datatables

### ISSUE THREAD

**Issue by franc3000** [franc3000/bartok#20]
http://bartok.herokuapp.com/regions/CO-Jake

http://datatables.net/ does not appear to be installed on the heroku server.

It should break into page entries like:

![image](https://cloud.githubusercontent.com/assets/10376582/13909766/f30fe618-eee6-11e5-8d6d-01b884eeef40.png)

It should also show filter sliders, that are not displaying.

![image](https://cloud.githubusercontent.com/assets/10376582/13909886/4cb07876-eee8-11e5-979b-340c0f13dc22.png)

https://github.com/franc3000/bartok/blob/bfeb3c024e6b934ba2bb4cd30c86a4f1550160f1/bartok/static/js/script.js

**Comment by nmb10** [comment]
Can't reproduce. Tryed firefox and chrome. This is what I see.
![table](https://cloud.githubusercontent.com/assets/207207/14058146/0aa103ea-f331-11e5-8ce1-ffabc0e1fe4a.png)

@franc3000 Do you still see the error?

**Comment by franc3000** [comment]
I dont see the error any more
