### ISSUE TITLE
Overview charting

### ISSUE THREAD

**Issue by franc3000** [franc3000/bartok#26]
https://bartok.herokuapp.com/regions/overview/CO-Jake

On the overview page, create a set of histograms like:

![image](https://cloud.githubusercontent.com/assets/10376582/14110413/f19a8c10-f58b-11e5-8d88-14839c79b6c5.png)

**Comment by franc3000** [comment]
Charts don’t have to be in a 3x3 grid, they can be displayed 1 after the other

**Comment by nmb10** [comment]
Done with minimal setup. Will improve on demand.
http://bartok.herokuapp.com/regions/overview/CO-Jake

* The query I used to get data:
```sql
SELECT total_assessed_value,
    bldg_living_area,
    lot_area,
    year(curdate()) - sold_append.year_built as house_age,
    bedrooms,
    bathrooms,
    improved_pct,
    length_of_ownership
FROM sold_append;
```
There is one problem I couldn't solve - page displays the overview of the region, but I didn't find the way how to filter the table by region. @franc3000  can you suggest appropriate field (or join)?

* lot_area, bathrooms and bedrooms columns have string types. This looks like a bug. @franc3000  should I create an issue for that?

**Comment by franc3000** [comment]
@nmb10 you can filter using the dataset and the county field, both specified in the row of the regions table.

```sql
where dataset='sow003' and county='EL PASO'
```

**Comment by franc3000** [comment]
@nmb10 can you set a max for the values by percentile? this will remove upper limit outliers and make the charts look better.

http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.percentile.html

`numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)`

```python
column_content = df[column].astype(float).dropna()

percentile90 = numpy.percentile(column_content, 90)
column_content = column_content < percentile90
```

**Comment by nmb10** [comment]
Done. The snippet given convert values to True/False. I did it this way instead:
```python
column_content = column_content[column_content < percentile90]
```
