### ISSUE TITLE
ProgrammingError: (_mysql_exceptions.ProgrammingError) (1146, "Table 'models_investor.investor_93_test' doesn't exist")

### ISSUE THREAD

**Issue by nmb10** [franc3000/bartok#29]
http://bartok.herokuapp.com/models/investor/93/positives

Test dataset table does not exist, but investor does. @franc3000  how bartok should behave on such situation? Is it expected state of the database?

**Comment by franc3000** [comment]
@nmb10 new schema, dont need to fix this
