### ISSUE TITLE
New layout and structure

### ISSUE THREAD

**Issue by franc3000** [franc3000/bartok#33]
Each table in the investor hierarchy can drill down to a more granular level.

```
investor_region
investor_config
investor_model
```

region_id --> config_id --> model_id

Each table is a page that can be found by clicking on the link.

List all regions
/region/

List all configs for region
/region/{region_name}/config

List all models for config
/region/{region_name}/config/{config_id}/model

In the models list page, display fields in the table:
- timestamp
- roc_auc
- settings

/region/{region_name}/config/{config_id}/model/{model_id}
In the model page, we can display all the specifics

Table for `feature_importances`
Table for `positives`
Table for `false_positives`
Etc.

**Comment by nmb10** [comment]
@franc3000 what type of chart to display as ROC chart? investor_model.roc is a text field.

**Comment by franc3000** [comment]
@nmb10 i'll make ROC chart a new issue, i'm not sure yet

**Comment by nmb10** [comment]
Done.
