### ISSUE TITLE
Improve missing investor model test dataset error.

### ISSUE THREAD

**Issue by nmb10** [franc3000/bartok#40]
Always create `investor_<id>_test` table with investor creation or use warning level for log message.

Error message:

Failed to get 107 investor test dataset. Error: (_mysql_exceptions.ProgrammingError) (1146, "Table 'models_investor.investor_107_test' doesn't exist") [SQL: u'SELECT count(*) AS count_1 \nFROM (SELECT investor_107_test.`index` AS investor_107_test_index, investor_107_test.y_test AS investor_107_test_y_test, investor_107_test.p_1 AS investor_107_test_p_1, investor_107_test.p_pctile AS investor_107_test_p_pctile, investor_107_test.include AS investor_107_test_include, investor_107_test.property_address AS investor_107_test_property_address, investor_107_test.property_zip AS investor_107_test_property_zip, investor_107_test.last_market_sale_date AS investor_107_test_last_market_sale_date, investor_107_test.bldg_living_area AS investor_107_test_bldg_living_area, investor_107_test.combined_age_relative AS investor_107_test_combined_age_relative, investor_107_test.year_built AS investor_107_test_year_built, investor_107_test.combined_age AS investor_107_test_combined_age, investor_107_test.total_assessed_value AS investor_107_test_total_assessed_value \nFROM investor_107_test) AS anon_1']

**Comment by nmb10** [comment]
@franc3000  what is better solution here?

**Comment by franc3000** [comment]
@nmb10 use:
https://github.com/franc3000/datastore/issues/1
https://github.com/franc3000/datastore/issues/2
for investors for the website

**Comment by nmb10** [comment]
@franc3000  I asked different thing. For example there is investor model with id=1, but investor_1_test table does not exist. Is it normal or invalid state?
